# Generated by Django 5.0.7 on 2024-08-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0003_author_itemlist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
