# Generated by Django 5.0.7 on 2024-08-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0004_alter_itemlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='author',
        ),
    ]
