# Generated by Django 5.0.7 on 2024-08-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0007_alter_itemlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
